/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.libreria.vistas;


/**
 *
 * @author loren
 */
public class PanelReportes extends javax.swing.JPanel {

    /**
     * Creates new form PanelReportes
     */
    public PanelReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblGanancias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio" }));

        jButton1.setText("Ventas Del Mes");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Ganancias Totales");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Top 3 Libros");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        lblGanancias.setText("Total: $ 0,00");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Venta", "Libro", "Fecha", "Total ($)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGanancias))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(lblGanancias)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            com.libreria.dao.VentaDAO ventaDAO = new com.libreria.dao.VentaDAO();
            java.util.List<com.libreria.model.Venta> todasLasVentas = ventaDAO.consultarTodos();
            
            double total = todasLasVentas.stream().mapToDouble(v -> v.getTotal()).sum();
            
            lblGanancias.setText(String.format("Total: $ %.2f", total));
            
        } catch (Exception e) {
            System.out.println("Error al Calcular: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String mesSeleccionado = jComboBox1.getSelectedItem().toString();
            
            com.libreria.dao.VentaDAO ventaDAO = new com.libreria.dao.VentaDAO();
    java.util.List<com.libreria.model.Venta> todasLasVentas = ventaDAO.consultarTodos();
    
    java.util.List<com.libreria.model.Venta> ventasFiltradas;
            ventasFiltradas = todasLasVentas.stream()
                    .filter(v -> v.getMes().toString().equals(mesSeleccionado))
                    .toList();
    
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    for (com.libreria.model.Venta v : ventasFiltradas) {
        Object[] fila = {v.getId(), v.getLibro(), v.getFecha(), v.getTotal()};
                
        modelo.addRow(fila);
    }
        } catch (Exception e) {
    System.out.println("Error al filtrar: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
        com.libreria.dao.LibroDAO LibroDAO = new com.libreria.dao.LibroDAO();
        java.util.List<com.libreria.model.Libro> todoslosLibros = LibroDAO.consultarTodos();
        
        java.util.List<com.libreria.model.Libro> top3 = todoslosLibros.stream()
        .sorted(java.util.Comparator.comparingInt(com.libreria.model.Libro::getcantidadVendida).reversed())
        .limit (3)
        .collect(java.util.stream.Collectors.toList());
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new Object[]{"ID Venta", "Titulo", "Detalle", "Cant. Vendida"});
        
        for (com.libreria.model.Libro libro : top3) {
            Object[] fila = {libro.getId(), libro.getTitulo(), "Top Vendido", libro.getcantidadVendida()};
            modelo.addRow(fila);
        }
    } catch (Exception e) {
   System.err.println("Error al procesar el Top 3 de libros: " + e.getMessage());
    }
}      

        private Object limit(int i) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGanancias;
    // End of variables declaration//GEN-END:variables

