/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.libreria.vistas;

/**
 *
 * @author Conra
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        // 1. Centrar la ventana en la pantalla al abrir
    this.setLocationRelativeTo(null);
    
    // 2. Definir un tamaño mínimo para que el usuario no la achique de más y rompa el diseño
    this.setMinimumSize(new java.awt.Dimension(1000, 700));
        
        
        
        
        
        // 1. Creamos la Vista (la pantalla "tonta")
com.libreria.vistas.PanelClientes vistaClientes = new com.libreria.vistas.PanelClientes();

// 2. Creamos el DAO (la conexión a MySQL)
com.libreria.dao.ClienteDAO daoClientes = new com.libreria.dao.ClienteDAO();

// 3. Creamos el Controlador y le pasamos la Vista y el DAO para que los una
com.libreria.controladores.ClienteControlador controladorClientes = new com.libreria.controladores.ClienteControlador(vistaClientes, daoClientes);

// 4. Finalmente, agregamos la Vista (que ya está "enchufada" y funcionando) a la pestaña
jTabbedPane1.addTab("Gestión de Clientes", vistaClientes);
        
        
        // Instanciación del módulo de Ventas con desacoplamiento arquitectónico
com.libreria.vistas.PanelVentas vistaVentas = new com.libreria.vistas.PanelVentas();
com.libreria.dao.VentaDAO daoVentas = new com.libreria.dao.VentaDAO();
com.libreria.controladores.VentaControlador controladorVentas = new com.libreria.controladores.VentaControlador(vistaVentas, daoVentas);

jTabbedPane1.addTab("Punto de Venta", vistaVentas);
        
        

// Instanciación del módulo de Gestión de Libros
com.libreria.vistas.PanelLibros vistaLibros = new com.libreria.vistas.PanelLibros();
com.libreria.dao.LibroDAO daoLibros = new com.libreria.dao.LibroDAO();
com.libreria.controladores.LibroControlador controladorLibros = new com.libreria.controladores.LibroControlador(vistaLibros, daoLibros);

jTabbedPane1.addTab("Inventario de Libros", vistaLibros);






    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
       // Inicializamos FlatLaf ANTES de crear la ventana
        try {
            // Activa el tema oscuro profesional (estilo modo oscuro de Windows/Mac):
//            com.formdev.flatlaf.FlatDarkLaf.setup();
            
            // Si preferís el tema claro, comentá la línea de arriba y descomentá esta:
             com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo inicializar FlatLaf", ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
